name: DCM Meeting CI
on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    strategy:
      matrix:
        node-version: [20.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Install packages
        run: npm install
      - name: Build client to server/public
        run: npm run build --prefix client
      - name: Run client and server tests
        run: npm run test
      - name: Run client e2e tests in production environment
        run: npm run ci:e2e
