name: Testing
on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: npm install
      - name: Build client to server/public
        run: npm run build --prefix client
      - name: Run client and server tests
        run: npm run test
      - name: Run client e2e tests in production environment
        run: npm run ci:e2e
      - name: Archive Cypress Snapshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-snapshots
          path: client/cypress/snapshots
